### PR TITLE
Implement commands and list in Protocol

### PR DESCRIPTION
**Pull request by tinsch**
Hi @Malwine,

I completed the three required features - a list for the commands in Protocol, the three services Subtract, Multiply and Hello and their functionality. Additionally I fixed a bug in the Add-Service (it was an array[0]/array[1] problem).

What we still need:
- [ ] Functionality to exchange messages via IP

Nice to have, if we find time:
- [x] Server.java: We might want to send back the result of the commands to the client.
- [x] Check input params for the correct type. E.g. Add foo 1 would not work.
- [x] Check for empty parameters in protocol and provide a fallback.
- [ ] Find out how to handle the constant list in Protocol. 
  - Should we use an Enum? Is this the proper way to use dynamic typing in a statically typed language?

I can also implement some of the stuff, or we only focus on the mandatory task on top of the list :)

Edit: I provided a try/catch solution in Protocol class. We now have a very verbose server, but no uncaught errors anymore. There is no explicit check for wrong types or empty parameter lists, though.

### CODE REVIEW

**Comment by Malwine** [comment]
@tinsch Nice!! Are you working on the last todo? Like: the messages via IP? 
yeah, I already saw the array bug earlier but knew you would find it 😼

**Comment by tinsch** [comment]
i'm working at the "sending back result" feature, and am about to commit it. I don't really know how to do sending messages via IP thing without being able to test it with another device...

**Comment by Malwine** [comment]
@tinsch Yes, I'll be there and we'll figure it out 👯

**Comment by tinsch** [comment]
@Malwine yesss <3

**Comment by Malwine** [comment]
😍 💯 ❤️ 🍭 🎉

**Pull request merged**
